spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password: root
    #可以不用配置 driver-class-name: com.mysql.jdbc.Driver
  application:
    name: User-Service
mybatis:
  type-aliases-package: cn.arvin.pojo
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka,http://127.0.0.1:10011/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1   # 指定自己的ip信息，不指定的话会自己寻找
    lease-renewal-interval-in-seconds: 10   # 服务续约(renew)的间隔，默认为30秒
    lease-expiration-duration-in-seconds: 5 # 服务失效时间，默认值90秒
    instance-id: ${spring.application.name}:${server.port} # 可不配置