server:
  port: 10010

spring:
  application:
    name: Eureka-Server # 服务名称唯一

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10011/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # lease-renewal-interval-in-seconds: 10   # 服务续约(renew)的间隔，默认为30秒
    # lease-expiration-duration-in-seconds: 5 # 服务失效时间，默认值90秒
    instance-id: ${spring.application.name}:${server.port} # 可不配置
  server:
    # enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）